name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: ${{ github.repository_owner == 'projectshadowos' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install and build
        run: |
          pnpm install
          pnpm run postinstall
          pnpm run build

      - name: Get version from package.json
        id: get_version
        run: |
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: brew install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view "v${{ env.VERSION }}" > /dev/null 2>&1; then
            echo "release_exists=true" >> $GITHUB_ENV
          else
            echo "release_exists=false" >> $GITHUB_ENV
          fi

      - name: Create tag
        if: env.release_exists == 'false'
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create release
        if: env.release_exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh release create "v${{ env.VERSION }}" --title "v${{ env.VERSION }}" --notes "Release v${{ env.VERSION }}"

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          pnpm exec electron-builder -- --publish always --win --linux